src/MainBundle/Entity/Enquete.php
<?php

namespace MainBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Enquete
 *
 * @ORM\Table(name="enquete")
 * @ORM\Entity(repositoryClass="MainBundle\Repository\EnqueteRepository")
 */
class Enquete
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     */
    private $description;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="start_date", type="datetime")
     */
    private $startDate;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="end_date", type="datetime")
     */
    private $endDate;

    /**
     * @var boolean
     *
     * @ORM\Column(name="published", type="boolean")
     */
    private $published;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Enquete
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Enquete
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set startDate
     *
     * @param \DateTime $startDate
     *
     * @return Enquete
     */
    public function setStartDate($startDate)
    {
        $this->startDate = $startDate;

        return $this;
    }

    /**
     * Get startDate
     *
     * @return \DateTime
     */
    public function getStartDate()
    {
        return $this->startDate;
    }

    /**
     * Set endDate
     *
     * @param \DateTime $endDate
     *
     * @return Enquete
     */
    public function setEndDate($endDate)
    {
        $this->endDate = $endDate;

        return $this;
    }

    /**
     * Get endDate
     *
     * @return \DateTime
     */
    public function getEndDate()
    {
        return $this->endDate;
    }

    /**
     * Set published
     *
     * @param boolean $published
     *
     * @return Enquete
     */
    public function setPublished($published)
    {
        $this->published = $published;

        return $this;
    }

    /**
     * Get published
     *
     * @return boolean
     */
    public function getPublished()
    {
        return $this->published;
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return $this->title;
    }
}

src/MainBundle/Form/EnqueteType.php
<?php

namespace MainBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Tests\Extension\Core\Type\CheckboxTypeTest;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EnqueteType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', null, ['label' => 'Enquêtenaam'])
            ->add('description', null, ['label' => 'Beschrijving'])
            ->add('startDate', DateTimeType::class,[
                'date_format' => 'dd MM yyyy',
                'label' => 'Startdatum',
            ])
            ->add('endDate', DateTimeType::class,[
                'date_format' => 'dd MM yyyy',
                'label' => 'Einddatum',
            ])
            ->add('published', CheckboxType::class, [
                'label' => 'Publiceren',
                'required' => false,
            ]);
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'MainBundle\Entity\Enquete'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'mainbundle_enquete';
    }


}

src/MainBundle/Form/ProfileType.php
<?php

namespace MainBundle\Form;

use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormTypeInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class ProfileType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstname', null, [
                'label' => 'Voornaam'
            ])
            ->add('lastname', null, [
                'label' => 'Achternaam'
            ])
            ->add('gender', ChoiceType::class, array(
                'choices'   => array(
                    'Man'       => "Man",
                    'Vrouw'     => "Vrouw"
                ),
                'label'     => 'Geslacht',
            ))
            ->add('birthdate', DateType::class, array(
                'format' => 'dd MM yyyy',
                'label' => 'Geboortedatum',
                'years' => range(date('Y') - 107, date('Y'))
            ))
            ->add('address', null, [
                'label' => 'Adres',
            ])
            ->add('postal', null, [
                'label' => 'Postcode'
            ])
            ->add('city', null, [
                'label' => 'Woonplaats'
            ])
            ->add('phone', null, [
                'label' => 'Telefoonnummer'
            ])
            ->add('bankaccount', null, [
                'label' => 'Bankrekening'
            ])
        ;
    }

    public function getParent()
    {
        return 'FOS\UserBundle\Form\Type\ProfileFormType';

        // Or for Symfony < 2.8
        // return 'fos_user_registration';
    }

    public function getBlockPrefix()
    {
        return 'mainbundle_user';
    }

    // For Symfony 2.x
    public function getName()
    {
        return $this->getBlockPrefix();
    }
}

src/MainBundle/Controller/EnqueteController.php
<?php

namespace MainBundle\Controller;

use MainBundle\Entity\Enquete;
use MainBundle\Entity\Question;
use MainBundle\Entity\Answer;
use MainBundle\Form\EnqueteType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;

/**
 * Enquete controller.
 *
 * @Route("enquete")
 */
class EnqueteController extends Controller
{
    /**
     * Lists all enquete entities.
     *
     * @Route("/", name="enquete_index")
     * @Method("GET")
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();
        $dateTime = new \DateTime("now");

        $enquetes = $em->getRepository('MainBundle:Enquete')->findBy(array(), array('id' => 'DESC'));

        return $this->render('@Main/enquete/index.html.twig', array(
            'enquetes' => $enquetes,
            'dateTime' => $dateTime,
        ));
    }

    /**
     * Creates a new enquete entity.
     *
     * @Route("/new", name="enquete_new")
     * @Method({"GET", "POST"})
     */
    public function newAction(Request $request)
    {
        $enquete = new Enquete();
        $enquete->setStartDate(new \DateTime("now + 0 day 12:00"));
        $enquete->setEndDate(new \DateTime("now + 2 weeks 1 day 12:00"));

        $form = $this->createForm('MainBundle\Form\EnqueteType', $enquete);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($enquete);
            $em->flush($enquete);

            return $this->redirectToRoute('question_new', array('enquetenaam' => $enquete->getTitle()));
        }

        return $this->render('@Main/enquete/new.html.twig', array(
            'enquete' => $enquete,
            'form' => $form->createView(),
        ));
    }

    /**
     * Finds and displays a enquete entity.
     *
     * @Route("/{id}", name="enquete_show")
     * @Method({"GET", "POST"})
     */
    public function showAction(Request $request, Enquete $enquete)
    {
        $em = $this->getDoctrine()->getManager();
        $user = $this->getUser();
        $dateTime = new \DateTime("now");

        $questions = $em->getRepository('MainBundle:Question')->findBy(array('enqueteId' => $enquete->getId()));
        $choices = $em->getRepository('MainBundle:Choice')->findAll();

        if ($this->get('security.authorization_checker')->isGranted('ROLE_ADMIN')) {
            $answers = $em->getRepository('MainBundle:Answer')->findAll();
        }
        else {
            $answers = $em->getRepository('MainBundle:Answer')->findBy(array('user' => $user));
        }

        $allAnswers = $em->getRepository('MainBundle:Answer')->findAll();

        $deleteForm = $this->createDeleteForm($enquete);

//        $payment = $em->getRepository('MainBundle:Payment')->findOneBy(array('userId' => $user, 'endDate' => $dateTime));

        $query = $em->createQuery(
            'SELECT p
            FROM MainBundle:Payment p
            WHERE p.userId = :user 
            AND p.endDate > :date '
        )->setParameter('user', $user)
        ->setParameter('date', $dateTime);
        $payment = $query->getResult();

        if ($payment == null)
        {
            $hasPaid = null;
        }
        else
        {
            $hasPaid = true;
        }

        if ($_SERVER['REQUEST_METHOD'] == 'POST'){
            $i = 0;
            foreach ($questions as $question)
            {
                $i++;
                $answer = new Answer();
                $answer->setUser($user);
                $answer->setChoiceId($_POST['radio-'.$i]);
                $em = $this->getDoctrine()->getManager();
                $em->persist($answer);
                $em->flush();
            }

            return $this->redirect($request->getUri());
        }

        return $this->render('@Main/enquete/show.html.twig', array(
            'enquete' => $enquete,
            'dateTime' => $dateTime,
            'questions' => $questions,
            'choices' => $choices,
            'answers' => $answers,
            'show' => true,
            'hasPaid' => $hasPaid,
            'userId' => $user,
            'allAnswers' => $allAnswers,
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing enquete entity.
     *
     * @Route("/{id}/edit", name="enquete_edit")
     * @Method({"GET", "POST"})
     */
    public function editAction(Request $request, Enquete $enquete)
    {
        $deleteForm = $this->createDeleteForm($enquete);
        $editForm = $this->createForm('MainBundle\Form\EnqueteType', $enquete);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('enquete_edit', array('id' => $enquete->getId()));
        }

        return $this->render('@Main/enquete/edit.html.twig', array(
            'enquete' => $enquete,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Deletes a enquete entity.
     *
     * @Route("/{id}", name="enquete_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, Enquete $enquete)
    {
        $form = $this->createDeleteForm($enquete);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($enquete);
            $em->flush($enquete);
        }

        return $this->redirectToRoute('enquete_index');
    }

    /**
     * Creates a form to delete a enquete entity.
     *
     * @param Enquete $enquete The enquete entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(Enquete $enquete)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('enquete_delete', array('id' => $enquete->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }
}

src/MainBundle/Resources/views/enquete/edit.html.twig
{% extends '@Main/base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('bundles/main/css/button.css') }}">
{% endblock %}

{% block body %}
    {% if is_granted ('ROLE_ADMIN') %}
<div class="col-md-6 col-md-offset-3 thumbnail" style="padding: 20px 20px 50px 20px;background-color: #f7f7f7;" >
        <h1>Enquête aanpassen</h1>

        {{ form_start(edit_form) }}
            {{ form_widget(edit_form) }}
            <input class="btn btn-success" type="submit" value="Opslaan" />
        {{ form_end(edit_form) }}


        <a class="btn btn-default" href="{{ path('enquete_index') }}">Terug naar overzicht</a>

        {{ form_start(delete_form) }}
            <input class="btn btn-danger" type="submit" value="Verwijderen">
        {{ form_end(delete_form) }}
</div>
    {% else %}
        <div>
            <h3>Helaas, u kunt deze pagina niet bekijken.</h3>
            <p>Log in als Administrator om de pagina weer te geven.</p>
        </div>
    {% endif %}
{% endblock %}

src/MainBundle/Resources/views/enquete/index.html.twig
{% extends '@Main/base.html.twig' %}

{% block body %}
    <div class="container">
        <h1>Enquête overzicht
        {% if is_granted ('ROLE_ADMIN') %}
            <a class=" btn btn-success" href="{{ path('enquete_new') }}">+ Enquête</a>
        {% endif %}
        </h1>

        <div class="row">
            {% for enquete in enquetes  %}
                {% if is_granted ('ROLE_ADMIN') %}
                    <div class="col-sm-6 col-md-4">
                        <div class="thumbnail">
                            <div class="caption">
                                <div class="row">
                                    <div class="col-sm-10">
                                        <h3>{{ enquete.title }}</h3>
                                        <p>{{ enquete.description|length > 35 ? enquete.description|slice(0, 35) ~ '...' : enquete.description }}</p>
                                        <p>
                                            Starttijd: {% if enquete.startDate %}{{ enquete.startDate|date('d-m-y H:i') }}{% endif %}
                                            <br>
                                            Eindtijd: {% if enquete.endDate %}{{ enquete.endDate|date('d-m-y H:i') }}{% endif %}
                                        </p>
                                        <p>
                                            <a href="{{ path('enquete_edit', { 'id': enquete.id }) }}" class="btn btn-primary" role="button">Wijzigen</a>
                                            <a href="{{ path('enquete_show', { 'id': enquete.id }) }}" class="btn btn-info" role="button">Weergeven</a>
                                        </p>
                                    </div>
                                    <div class="col-sm-2">
                                        {%  if enquete.published %} <img class="vinkje" src="{{ asset('bundles/main/images/vinkje.png') }}"/>{% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% else %}
                    {% if enquete.published %}
                        {% if enquete.startDate < dateTime and enquete.endDate > dateTime %}
                            <div class="col-sm-6 col-md-4">
                                <div class="thumbnail">
                                    <div class="caption">
                                        <h3><b>{{ enquete.title }}</b></h3>
                                        <hr>
                                        <p>{{ enquete.description|length > 250 ? enquete.description|slice(0, 250) ~ '...' : enquete.description }}</p>
                                        <hr>
                                        <p>
                                            <a href="{{ path('enquete_show', { 'id': enquete.id }) }}" class="btn btn-info" role="button">Invullen</a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        {% elseif enquete.endDate < dateTime %}
                            <div class="col-sm-6 col-md-4">
                                <div class="thumbnail">
                                    <div class="caption">
                                        <h3>{{ enquete.title }}</h3>
                                        <hr>
                                        <h4><b>Deze enquête is gesloten!</b></h4>
                                        <p></p>
                                        <hr>
                                        <p>
                                            <a href="{{ path('enquete_show', { 'id': enquete.id }) }}" class="btn btn-info" role="button">Bekijk resultaten</a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

src/MainBundle/Resources/views/enquete/new.html.twig
{% extends '@Main/base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('bundles/main/css/button.css') }}">
{% endblock %}

{% block body %}
    {% if is_granted ('ROLE_ADMIN') %}
        <div class="col-md-6 col-md-offset-3 thumbnail" style="padding: 20px 20px 50px 20px;background-color: #f7f7f7;" >
            <h1>Enquête aanmaken</h1>

            {{ form_start(form) }}
            {{ form_widget(form) }}
            <input class="btn btn-success" type="submit" value="Opslaan" />
            {{ form_end(form) }}

            <a class="btn btn-default" href="{{ path('enquete_index') }}">Terug naar overzicht</a>
        </div>
    {% else %}
        <div>
            <h3>Helaas, u kunt deze pagina niet bekijken.</h3>
            <p>Log in als Administrator om de pagina weer te geven.</p>
        </div>
    {% endif %}
{% endblock %}

src/MainBundle/Resources/views/enquete/show.html.twig
{% extends '@Main/base.html.twig' %}

{% block title %}
    {% if is_granted ('ROLE_ADMIN') %}
        Bekijk: {{ enquete.title }}
    {% else %}
        Enquete: {{ enquete.title }}
    {% endif %}
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('bundles/main/css/button.css') }}">
{% endblock %}

{% for question in questions %}
    {% for choice in choices if choice.questionId == question.id %}
        {% for answer in answers %}
            {% if answer.choiceId == choice.id %}
                {% set show = false %}
            {% endif %}
        {% endfor %}
    {% endfor %}
{% endfor %}

{% block body %}
    {% if is_granted ('ROLE_ADMIN') %}
        <h1>Enquete</h1>

        <table class="table table-striped">
            <tbody>
            <tr>
                <th>Id</th>
                <td>{{ enquete.id }}</td>
            </tr>
            <tr>
                <th>Titel</th>
                <td>{{ enquete.title }}</td>
            </tr>
            <tr>
                <th>Beschrijving</th>
                <td>{{ enquete.description }}</td>
            </tr>
            <tr>
                <th>Starttijd</th>
                <td>{% if enquete.startDate %}{{ enquete.startDate|date('d-m-Y H:i:s') }}{% endif %}</td>
            </tr>
            <tr>
                <th>Eindtijd</th>
                <td>{% if enquete.endDate %}{{ enquete.endDate|date('d-m-Y H:i:s') }}{% endif %}</td>
            </tr>
            <tr>
                <th>Gepubliceerd</th>
                <td>{% if enquete.published %}ja{% else %}nee{% endif %}</td>
            </tr>
            </tbody>
        </table>
        <div>
            <hr>
            {% set q = 1 %}
            {% for question in questions %}
                {% set total = 0.000001 %}
                {% for choice in choices if choice.questionId == question.id %}
                    {% for answer in answers %}
                        {% if answer.choiceId == choice.id %}
                            {% set total = total + 1 %}
                        {% endif %}
                    {% endfor %}
                {% endfor %}

                <p>Vraag {{ q }}: <b>{{ question.title }}</b></p>
                {% set a = 1 %}
                {% for choice in choices if choice.questionId == question.id %}
                    {% set count = 0 %}
                    {% for answer in answers %}
                        {% if answer.choiceId == choice.id %}
                            {% set count = count + 1 %}
                        {% endif %}
                    {% endfor %}
                    <div class="col-md-12">
                        <b> {{ choice.choice }} </b>
                        <div class="progress" style="width: 100px;">
                            <div class="progress-bar" role="progressbar" aria-valuenow="{{ count/total*100 }}" aria-valuemin="0" aria-valuemax="100" style="width:{{ count/total*100 }}%">
                                {{ (count/total*100)|number_format(0) }}%
                            </div>
                        </div>
                        <p>Aantal stemmen: {{ count }}</p><br>
                    </div>
                    {% set a = a+1 %}
                {% endfor %}
                {% set q = q+1 %}
                <hr>

            {% endfor %}
        </div>

        <a id="button" class="btn btn-default" href="{{ path('enquete_index') }}">Terug naar overzicht</a>

        <a id="button" class="btn btn-primary" href="{{ path('enquete_edit', { 'id': enquete.id }) }}">Wijzigen</a>

        {{ form_start(delete_form) }}
        <input id="button" class="btn btn-danger" type="submit" value="Verwijderen">
        {{ form_end(delete_form) }}

    {% elseif app.user %}
        {% if show == true %}
            {#{% if hasPaid == true %}#}
                {% if enquete.startDate < dateTime and enquete.endDate > dateTime %}
                    <div class="col-sm-6">
                        <hr>
                        <h2>{{ enquete.title }}</h2>
                        <p>{{ enquete.description }}</p>
                        <form name="enquete-{{ enquete.id }}" method="post">
                            {% for question in questions %}
                                <hr>
                                <p><b>{{ question.title }}</b></p>
                                {% for choice in choices if choice.questionId == question.id %}
                                    <div class="radio">
                                        <label><input type="radio" name="radio-{{ loop.parent.loop.index }}" value="{{ choice.id }}">{{ choice.choice }}</label>
                                    </div>
                                {% endfor %}

                            {% endfor %}
                            <hr>
                            <input class="btn btn-success" type="submit" value="Versturen" style="margin-bottom: 20px">
                        </form>
                    </div>
                    <div class="container">
                {% elseif enquete.endDate < dateTime %}
                    {% set q = 1 %}
                    {% for question in questions %}
                        {% set total = 0.000001 %}
                        {% for choice in choices if choice.questionId == question.id %}
                            {% for answer in allAnswers %}
                                {% if answer.choiceId == choice.id %}
                                    {% set total = total + 1 %}
                                {% endif %}
                            {% endfor %}
                        {% endfor %}

                        <p><b>{{ question.title }}</b></p>
                        {% set a = 1 %}
                        {% for choice in choices if choice.questionId == question.id %}
                            {% set count = 0 %}
                            {% for answer in allAnswers %}
                                {% if answer.choiceId == choice.id %}
                                    {% set count = count + 1 %}
                                {% endif %}
                            {% endfor %}
                            <ul>
                                <li>
                                    <b> {{ choice.choice }} </b>
                                    <div class="progress" style="width: 100px;">
                                        <div class="progress-bar" role="progressbar" aria-valuenow="{{ count/total*100 }}" aria-valuemin="0" aria-valuemax="100" style="width:{{ count/total*100 }}%">
                                            {{ (count/total*100)|number_format(0) }}%
                                        </div>
                                    </div>
                                    Aantal stemmen: {{ count }}
                                </li>
                            </ul>
                            {% set a = a+1 %}
                        {% endfor %}
                        {% set q = q+1 %}
                        <hr>
                    {% endfor %}
                    <a class="btn btn-info btn-lg" href="{{ path('enquete_index') }}">Terug naar overzicht</a>
                    </div>
                {% else %}
                    <div class="col-sm-6">
                        <h1>Oeps, er is iets misgegaan!</h1>
                        <p>
                            Deze enquête is momenteel niet in gebruik.
                        </p>
                        <p>Klik op de knop hieronder om terug te gaan naar het overzicht.</p>
                        <a class="btn btn-info btn-lg" href="{{ path('enquete_index') }}">Terug naar overzicht</a>
                    </div>
                {% endif %}
            {#{% else %}#}
                {#<div class="col-sm-6">#}
                    {#<h1>Oeps, er is iets misgegaan!</h1>#}
                    {#<p>#}
                        {#Waarschijnlijk heeft u nog geen betaling voldaan aan Zoetermeer Vooruit.#}
                        {#U kunt pas enquêtes invullen op het moment dat u een geldig lidmaatschap heeft.#}
                    {#</p>#}
                    {#<p>Klik op de knop hieronder om terug te gaan naar het overzicht.</p>#}
                    {#<a class="btn btn-info btn-lg" href="{{ path('enquete_index') }}">Terug naar overzicht</a>#}
                {#</div>#}
            {#{% endif %}#}
        {% elseif show != true and enquete.endDate < dateTime %}
            {% set q = 1 %}
            {% for question in questions %}
                {% set total = 0.000001 %}
                {% for choice in choices if choice.questionId == question.id %}
                    {% for answer in allAnswers %}
                        {% if answer.choiceId == choice.id %}
                            {% set total = total + 1 %}
                        {% endif %}
                    {% endfor %}
                {% endfor %}

                <p><b>{{ question.title }}</b></p>
                {% set a = 1 %}
                {% for choice in choices if choice.questionId == question.id %}
                    {% set count = 0 %}
                    {% for answer in allAnswers %}
                        {% if answer.choiceId == choice.id %}
                            {% set count = count + 1 %}
                        {% endif %}
                    {% endfor %}
                    <ul>
                        <li>
                            <b> {{ choice.choice }} </b>
                            <div class="progress" style="width: 100px;">
                                <div class="progress-bar" role="progressbar" aria-valuenow="{{ count/total*100 }}" aria-valuemin="0" aria-valuemax="100" style="width:{{ count/total*100 }}%">
                                    {{ (count/total*100)|number_format(0) }}%
                                </div>
                            </div>
                            Aantal stemmen: {{ count }}
                        </li>
                    </ul>
                    {% set a = a+1 %}
                {% endfor %}
                {% set q = q+1 %}
                <hr>
            {% endfor %}
            <a class="btn btn-info btn-lg" href="{{ path('enquete_index') }}">Terug naar overzicht</a>
        {% else %}
            <div class="col-sm-6">
                <h1>Hartelijk bedankt!</h1>
                <p>U heeft deze enquête ingevuld.</p>
                <p>Klik op de knop hieronder om terug te gaan naar het overzicht.</p>
                <a class="btn btn-info btn-lg" href="{{ path('enquete_index') }}">Terug naar overzicht</a>
            </div>
        {% endif %}
    {% else %}
        <div>
            <h3>Helaas, u kunt deze pagina niet bekijken.</h3>
            <p>Log in als Administrator om de pagina weer te geven.</p>
        </div>
    {% endif %}
{% endblock %}